import "@/styles/globals.css";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import WalletProviders from "./WalletProviders";
import { getConfig } from "./wagmi";
import { cookieToInitialState } from "wagmi";
import { headers } from 'next/headers';
import  Header  from "@/components/Header";
import  Footer  from "@/components/Footer";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const headersList = await headers();
  const initialState = cookieToInitialState(
    getConfig(),
    headersList.get('cookie'),
  )
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletProviders initialState={initialState}>
          <Header/>
          {children}
          <Footer/>
        </WalletProviders>
      </body>
    </html>
  )
}
